#!/usr/bin/env python3
"""
TopicConfig - Data structure for topic-specific educational content.

Holds ALL topic-specific content needed by the chatbot:
prompts, misconceptions, lesson material, evaluation rubric, etc.
Generated dynamically by TopicGenerator from teacher's learning material.
"""

import json
from dataclasses import dataclass, field, asdict
from typing import List, Optional


@dataclass
class TopicConfig:
    """
    Complete topic configuration generated from teacher's learning material.
    Replaces all hardcoded prompt content — making the chatbot fully generic.
    """

    # --- Core Identity ---
    topic_name_en: str = ""
    topic_name_he: str = ""
    subject_area_en: str = ""
    subject_area_he: str = ""
    target_age: int = 10
    bot_knowledge_level: int = 1  # 1=struggling, 2=basic knowledge, 3=advanced+misleading

    # --- Learning Content ---
    key_concepts_en: List[str] = field(default_factory=list)
    key_concepts_he: List[str] = field(default_factory=list)
    key_terms_en: List[str] = field(default_factory=list)
    key_terms_he: List[str] = field(default_factory=list)
    common_misconceptions_en: List[str] = field(default_factory=list)
    common_misconceptions_he: List[str] = field(default_factory=list)
    good_examples_en: List[str] = field(default_factory=list)
    good_examples_he: List[str] = field(default_factory=list)

    # --- Full AI Prompts (generated by TopicGenerator) ---
    student_persona_en: str = ""
    student_persona_he: str = ""
    student_initial_message_en: str = ""
    student_initial_message_he: str = ""
    mentor_system_prompt_en: str = ""
    mentor_system_prompt_he: str = ""
    evaluation_prompt_en: str = ""
    evaluation_prompt_he: str = ""

    # --- Lesson Content (for preparation screen) ---
    lesson_summary_en: str = ""
    lesson_summary_he: str = ""

    # --- Raw Input (preserved for reference) ---
    raw_material: str = ""

    # --- Metadata ---
    generation_model: str = ""
    config_version: str = "1.0"

    # ================================================================
    # LANGUAGE-AWARE ACCESSORS
    # ================================================================

    def get_topic_name(self, lang: str = "en") -> str:
        return self.topic_name_he if lang == "he" else self.topic_name_en

    def get_subject_area(self, lang: str = "en") -> str:
        return self.subject_area_he if lang == "he" else self.subject_area_en

    def get_key_concepts(self, lang: str = "en") -> List[str]:
        return self.key_concepts_he if lang == "he" else self.key_concepts_en

    def get_key_terms(self, lang: str = "en") -> List[str]:
        return self.key_terms_he if lang == "he" else self.key_terms_en

    def get_misconceptions(self, lang: str = "en") -> List[str]:
        return self.common_misconceptions_he if lang == "he" else self.common_misconceptions_en

    def get_good_examples(self, lang: str = "en") -> List[str]:
        return self.good_examples_he if lang == "he" else self.good_examples_en

    def get_student_persona(self, lang: str = "en") -> str:
        return self.student_persona_he if lang == "he" else self.student_persona_en

    def get_student_initial_message(self, lang: str = "en") -> str:
        return self.student_initial_message_he if lang == "he" else self.student_initial_message_en

    def get_mentor_prompt(self, lang: str = "en") -> str:
        return self.mentor_system_prompt_he if lang == "he" else self.mentor_system_prompt_en

    def get_evaluation_prompt(self, lang: str = "en") -> str:
        return self.evaluation_prompt_he if lang == "he" else self.evaluation_prompt_en

    def get_lesson_summary(self, lang: str = "en") -> str:
        return self.lesson_summary_he if lang == "he" else self.lesson_summary_en

    def get_bot_knowledge_level(self) -> int:
        return self.bot_knowledge_level

    # ================================================================
    # SERIALIZATION
    # ================================================================

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> 'TopicConfig':
        """Deserialize from dictionary."""
        # Filter out unknown keys to be forward-compatible
        valid_fields = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in valid_fields}
        return cls(**filtered)

    def save_to_file(self, filepath: str):
        """Save config to JSON file for reuse."""
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(self.to_dict(), f, ensure_ascii=False, indent=2)
        print(f"TopicConfig saved to {filepath}")

    @classmethod
    def load_from_file(cls, filepath: str) -> 'TopicConfig':
        """Load config from previously saved JSON file."""
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"TopicConfig loaded from {filepath}")
        return cls.from_dict(data)

    # ================================================================
    # VALIDATION
    # ================================================================

    def is_valid(self) -> bool:
        """Check that all essential fields are populated."""
        required_strings = [
            self.topic_name_en, self.student_persona_en,
            self.student_initial_message_en, self.mentor_system_prompt_en,
            self.evaluation_prompt_en, self.lesson_summary_en,
        ]
        required_lists = [
            self.key_concepts_en, self.key_terms_en,
            self.common_misconceptions_en,
        ]
        return (
            all(s.strip() for s in required_strings)
            and all(len(lst) > 0 for lst in required_lists)
        )

    def __repr__(self):
        return (
            f"TopicConfig(topic='{self.topic_name_en}', "
            f"subject='{self.subject_area_en}', "
            f"age={self.target_age}, "
            f"concepts={len(self.key_concepts_en)}, "
            f"terms={len(self.key_terms_en)}, "
            f"misconceptions={len(self.common_misconceptions_en)})"
        )


# Quick test
if __name__ == "__main__":
    config = TopicConfig(
        topic_name_en="Photosynthesis",
        topic_name_he="פוטוסינתזה",
        subject_area_en="Biology",
        subject_area_he="ביולוגיה",
        key_concepts_en=["Light energy → chemical energy", "Chloroplasts"],
        key_terms_en=["Chlorophyll — green pigment"],
        common_misconceptions_en=["Plants get food from soil"],
    )
    print(config)
    print(f"Valid: {config.is_valid()}")

    # Test serialization
    d = config.to_dict()
    config2 = TopicConfig.from_dict(d)
    print(f"Round-trip: {config2.topic_name_en}")
    print("TopicConfig OK!")
